Final: false
R0: false
R20: false
aspect_ratio: 1.0
batch_size: 1
checkpoints_dir: ./pix2pix/checkpoints
colorize_results: false
crop_size: 672
data_dir: null
dataroot: null
dataset_mode: depthmerge
depthNet: null
direction: AtoB
display_winsize: 256
epoch: latest
eval: false
generatevideo: null
gpu_ids:
- 0
init_gain: 0.02
init_type: normal
input_nc: 4
isTrain: false
load_iter: 0
load_size: 672
max_dataset_size: 10000
max_res: .inf
model: pix2pix4depth
n_layers_D: 3
name: void
ndf: 64
netD: basic
netG: unet_1024
net_receptive_field_size: null
ngf: 64
no_dropout: false
no_flip: false
norm: none
num_test: 50
num_threads: 4
output_dir: null
output_nc: 1
output_resolution: null
phase: test
pix2pixsize: null
preprocess: resize_and_crop
savecrops: null
savewholeest: null
serial_batches: false
suffix: ''
verbose: false
